### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by shelomentsevd** [DmitriyShelomentsev/ants_simulation#1]
- [x] Написать класс отвечающий за феромоны.
- [x] Поиграться с цветами.
- [ ] Написать класс "Еды"
- [ ] Написать поведение для муравьёв.
